services:
  mongodb:
    image: mongo:5.0.2
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    ports:
      - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
      - target: $MONGODB_DOCKER_PORT
        host_ip: 127.0.0.1
        # expose mongodb port to host to allow connection on db client
        published: $MONGODB_EXPOSED_PORT
        protocol: tcp
        mode: host
    volumes:
      - db:/data/db
  server:
    depends_on:
      - mongodb
    build: ./server
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
  client:
    depends_on:
      - server
    build: ./client
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $CLIENT_LOCAL_PORT:$CLIENT_DOCKER_PORT
    environment:
      - REACT_APP_API_URL=http://localhost:$NODE_LOCAL_PORT
volumes:
  db:
